<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../ContractScribe.Core/ContractScribe.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Framework" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Locator" />
    <PackageReference Include="Microsoft.NET.StringTools" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
  </ItemGroup>
</Project>
